import tesseract.motion_planners._tesseract_motion_planners


class SimpleMotionPlanner:
    def __init__(self, name: str = 'SIMPLE') -> None: ...

    def getName(self) -> str: ...

    def solve(self, request: tesseract.motion_planners._tesseract_motion_planners.PlannerRequest) -> tesseract.motion_planners._tesseract_motion_planners.PlannerResponse: ...

    def terminate(self) -> bool: ...

    def clear(self) -> None: ...

    def clone(self) -> tesseract.motion_planners._tesseract_motion_planners.MotionPlanner: ...

def generateInterpolatedProgram(instructions: "tesseract_planning::CompositeInstruction", env: "tesseract_environment::Environment", state_longest_valid_segment_length: float = 0.08726646259971647, translation_longest_valid_segment_length: float = 0.15, rotation_longest_valid_segment_length: float = 0.08726646259971647, min_steps: int = 1) -> "tesseract_planning::CompositeInstruction":
    """Generate an interpolated program from a composite instruction"""
